name: voila-pdf-demo
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# ---------------------------------
# dev env currently contains
# requirements for both UI and API
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab>=4.0.0
  - voila>=0.5.7
